use_frameworks!
platform :ios, '10.0'

target 'MGKeyboardAccessory_Example' do
  pod 'MGKeyboardAccessory/Rx', :path => '../'

  target 'MGKeyboardAccessory_Tests' do
    inherit! :search_paths
  end
end
