use_frameworks!
platform :ios, '8.3'

target 'MGKeyboardAccessory_Example' do
  pod 'MGKeyboardAccessory', :path => '../'

  target 'MGKeyboardAccessory_Tests' do
    inherit! :search_paths

    
  end
end
